import { CANDLE_DEFAULT_INTERVAL, CANDLE_INTERVALS } from '../../candles/constants/candle.constants.js';

export const INDICATOR_SUPPORTED_INTERVALS = CANDLE_INTERVALS;
export const INDICATOR_DEFAULT_INTERVAL = CANDLE_DEFAULT_INTERVAL;
export const INDICATOR_CANDLE_LIMIT = 250;

export const EMA_PERIODS = {
  ema9: 9,
  ema20: 20,
  ema200: 200
} as const;

export const TREND_VALUES = ['Bullish', 'Bearish', 'Neutral'] as const;

export const TREND_AGE_VALUES = ['Fresh', 'Developing', 'Old'] as const;

export const FRESH_CROSS_MAX_CANDLES = 8;
export const DEVELOPING_TREND_MAX_CANDLES = 20;

export const DISTANCE_BELOW_EMA200_BONUS_PERCENT = 3;
export const DISTANCE_BELOW_EMA200_PENALTY_PERCENT = 8;

export const SCORE_WEIGHTS = {
  belowEMA200: 25,
  bearishAlignment: 25,
  freshCross: 25,
  closeToEMA200: 25,
  farBelowEMA200Penalty: -20,
  oldTrendPenalty: -15
} as const;

export const SCORE_MIN = 0;
export const SCORE_MAX = 100;

export const EMA20_SLOPE_LOOKBACK = 5;
export const EMA200_SLOPE_LOOKBACK = 10;
export const EMA9_SLOPE_LOOKBACK = 5;
export const MOMENTUM_LOOKBACK = 5;

export const SLOPE_FLAT_THRESHOLD_PERCENT = 0.06;
export const SLOPE_STRONG_DOWN_THRESHOLD_PERCENT = -0.35;
export const SLOPE_MODERATE_DOWN_THRESHOLD_PERCENT = -0.12;
export const SLOPE_SCORE_FULL_DECLINE_PERCENT = 0.6;

export const SIDEWAYS_MAX_DISTANCE_FROM_EMA200_PERCENT = 1.2;
export const SIDEWAYS_OSCILLATION_LOOKBACK = 12;
export const SIDEWAYS_MIN_SIGN_FLIPS = 3;
export const SIDEWAYS_PRICE_SIGN_FLIPS_MIN = 4;
export const SIDEWAYS_TIGHT_RANGE_MAX_PERCENT = 1.4;
export const SIDEWAYS_LOW_ATR_MAX_PERCENT = 0.35;
export const SIDEWAYS_PENALTY_LIGHT = 10;
export const SIDEWAYS_PENALTY_MEDIUM = 18;
export const SIDEWAYS_PENALTY_HEAVY = 25;

export const VOLUME_AVERAGE_PERIOD = 20;
export const VOLUME_QUALITY_POOR_THRESHOLD = 0.8;
export const VOLUME_QUALITY_GOOD_THRESHOLD = 1.1;
export const VOLUME_QUALITY_EXCELLENT_THRESHOLD = 1.6;
export const VOLUME_SCORE_RATIO_EXCELLENT = 2.5;
export const VOLUME_SCORE_RATIO_STRONG = 2;
export const VOLUME_SCORE_RATIO_GOOD = 1.5;
export const VOLUME_SCORE_RATIO_FAIR = 1.2;
export const VOLUME_SCORE_RATIO_BASE = 1;

export const TREND_STRENGTH_MIN = 0;
export const TREND_STRENGTH_MAX = 10;

export const PRICE_EFFICIENCY_LOW_THRESHOLD = 0.8;
export const PRICE_EFFICIENCY_MEDIUM_THRESHOLD = 1.5;
export const MOMENTUM_SCORE_FULL_DECLINE_PERCENT = 3;

export const ELIGIBILITY_MIN_TREND_STRENGTH = 5;
export const ELIGIBILITY_MAX_SIDEWAYS_SCORE = 60;
export const ELIGIBILITY_MAX_DISTANCE_BELOW_EMA200_PERCENT = -3;
export const HIGH_PRIORITY_MAX_CANDLES_SINCE_CROSS = 3;
export const HIGH_PRIORITY_MIN_TREND_STRENGTH = 7;

export const SIDEWAYS_STAGE_MAX_SCORE = 60;
export const SIDEWAYS_STAGE_MIN_TREND_STRENGTH = 4;

export const EARLY_BREAKDOWN_MAX_CANDLES_SINCE_CROSS = 3;
export const EARLY_BREAKDOWN_MIN_TREND_STRENGTH = 7;
export const EARLY_BREAKDOWN_MAX_SIDEWAYS_SCORE = 20;

export const PULLBACK_ENTRY_MIN_CANDLES_SINCE_CROSS = 3;
export const PULLBACK_ENTRY_MAX_CANDLES_SINCE_CROSS = 12;
export const PULLBACK_ENTRY_MIN_TREND_STRENGTH = 6;
export const PULLBACK_ENTRY_MAX_SIDEWAYS_SCORE = 30;
export const PULLBACK_ENTRY_NEAR_EMA_MAX_DISTANCE_PERCENT = 0.8;

export const TREND_CONTINUATION_MIN_CANDLES_SINCE_CROSS = 13;
export const TREND_CONTINUATION_MIN_TREND_STRENGTH = 6;

export const LATE_TREND_OLD_MIN_CANDLES_SINCE_CROSS = 20;
export const LATE_TREND_DISTANCE_FROM_EMA200_PERCENT = -3;
export const LATE_TREND_LOW_PRICE_EFFICIENCY = 0.12;
export const LATE_TREND_WEAKENING_TREND_STRENGTH = 5;

export const ENTRY_STOP_BUFFER_PERCENT = 0.25;
export const ENTRY_SWING_LOOKBACK = 20;
export const ENTRY_SUPPORT_LOOKBACK = 20;
export const ENTRY_CONTINUATION_MAX_EMA20_DISTANCE_PERCENT = 1;
export const ENTRY_EARLY_BREAKDOWN_EXTENDED_DISTANCE_PERCENT = 1.5;
export const ENTRY_PULLBACK_NEAR_EMA9_DISTANCE_PERCENT = 0.5;

export const ENTRY_QUALITY_MAX = 100;
export const ENTRY_QUALITY_MIN = 0;
export const ENTRY_QUALITY_RR_HIGH = 3;
export const ENTRY_QUALITY_RR_MEDIUM = 2;
export const ENTRY_QUALITY_RR_LOW = 1.5;

export const TREND_SCORE_EXCELLENT_MIN = 85;
export const TREND_SCORE_GOOD_MIN = 70;
export const TREND_SCORE_AVERAGE_MIN = 55;

export const TREND_QUALITY_MAX_SCORE = 20;
export const TREND_QUALITY_LOOKBACK = 40;
export const TREND_QUALITY_EXCELLENT_MIN = 16;
export const TREND_QUALITY_GOOD_MIN = 12;
export const TREND_QUALITY_AVERAGE_MIN = 8;
export const TREND_QUALITY_HEAVY_EMA20_CROSS_COUNT = 6;
export const TREND_QUALITY_HEAVY_FAKE_BREAKOUT_COUNT = 4;
export const TREND_QUALITY_PULLBACK_BODY_RATIO_POOR = 1.15;
export const TREND_QUALITY_PULLBACK_BODY_RATIO_GOOD = 0.7;

export const ENTRY_SCORE_READY_MIN = 80;
export const ENTRY_SCORE_WATCH_MIN = 60;
export const ENTRY_SCORE_DEVELOPING_MIN = 30;

export const VERDICT_READY_TREND_MIN = 85;
export const VERDICT_READY_ENTRY_MIN = 80;
export const VERDICT_DEVELOPING_TREND_MIN = 70;

export const TRADE_DECISION_WEIGHTS = {
  trendScore: 0.4,
  entryScore: 0.3,
  multiTimeframe: 0.1,
  marketQuality: 0.1,
  riskReward: 0.1
} as const;

export const TRADE_DECISION_A_PLUS_MIN = 95;
export const TRADE_DECISION_STRONG_MIN = 85;
export const TRADE_DECISION_WATCH_MIN = 70;
export const TRADE_DECISION_WEAK_MIN = 55;

export const DECISION_TREND_MIN_STRENGTH = 6;
export const DECISION_TREND_MAX_SIDEWAYS_SCORE = 55;
export const DECISION_ENTRY_READY_EMA20_DISTANCE_MAX = 0.9;
export const DECISION_ENTRY_WATCH_EMA20_DISTANCE_MAX = 1.6;
export const DECISION_ENTRY_POOR_EMA20_DISTANCE_MIN = 2.4;
export const DECISION_MAX_ABS_EMA200_DISTANCE_PERCENT = 9;
export const DECISION_MAX_ABS_EMA20_EXTENSION_PERCENT = 2.4;
export const DECISION_HARD_BLOCK_RISK_REWARD_MIN = 1.6;
export const DECISION_HARD_BLOCK_ENTRY_SCORE_MIN = 20;
export const DECISION_DIRECTIONAL_MOVEMENT_MIN = 6;
export const DECISION_OLD_TREND_CANDLES_MIN = 20;
export const DECISION_MAJOR_SUPPORT_DISTANCE_PERCENT = 0.7;
export const DECISION_NEAR_SUPPORT_DISTANCE_PERCENT = 1.4;
export const DECISION_EXTREME_EXTENSION_PERCENT = 3.2;
export const DECISION_NEAR_SUPPORT_PENALTY = -4;
export const DECISION_SLIGHT_EXTENSION_PENALTY = -4;
export const DEBUG_CALIBRATION_MODE = false;

export const STRUCTURE_SWING_WINDOW = 2;
export const STRUCTURE_LOOKBACK_LIMIT = 80;
export const STRUCTURE_RETEST_TOLERANCE_PERCENT = 0.45;
export const STRUCTURE_FALSE_BREAK_RECLAIM_PERCENT = 0.25;
export const STRUCTURE_COMPRESSION_LOOKBACK = 12;
export const STRUCTURE_SQUEEZE_MAX_RANGE_PERCENT = 1.1;
export const STRUCTURE_TRIANGLE_RANGE_SHRINK_RATIO = 0.72;
export const STRUCTURE_MIN_SWINGS_FOR_QUALITY = 4;
export const STRUCTURE_STRONG_QUALITY_MIN = 7;
export const STRUCTURE_WEAK_QUALITY_MAX = 4;

export const STRUCTURE_PIVOT_LEFT_BARS = 2;
export const STRUCTURE_PIVOT_RIGHT_BARS = 2;
export const STRUCTURE_MIN_SWING_MOVE_PERCENT = 0.18;
export const STRUCTURE_RECENT_BOS_CANDLES = 8;
export const STRUCTURE_QUALITY_EXCELLENT_MIN = 8;
export const STRUCTURE_QUALITY_GOOD_MIN = 6;
export const STRUCTURE_CONFIDENCE_MAX = 100;

export const SUPPORT_RESISTANCE_TOUCH_TOLERANCE_PERCENT = 0.28;
export const SUPPORT_DISTANCE_NEAR_PERCENT = 1.2;
export const SUPPORT_DISTANCE_STRONG_WARNING_PERCENT = 0.7;
export const RESISTANCE_DISTANCE_NEAR_PERCENT = 1.2;
export const SUPPORT_RESISTANCE_LOOKBACK = 80;

export const LIQUIDITY_EQUAL_LEVEL_TOLERANCE_PERCENT = 0.18;
export const LIQUIDITY_PREVIOUS_DAY_CANDLES = 96;
export const LIQUIDITY_NEAR_DISTANCE_PERCENT = 1.1;

export const ATR_PERIOD = 14;
export const ATR_BASELINE_PERIOD = 30;
export const EXHAUSTION_IMPULSIVE_BODY_MULTIPLIER = 1.5;
export const EXHAUSTION_IMPULSIVE_LOOKBACK = 6;
export const EXHAUSTION_MIN_IMPULSIVE_CANDLES = 3;
export const EXHAUSTION_EMA20_EXTENDED_PERCENT = 1.8;
export const EXHAUSTION_EMA20_EXHAUSTED_PERCENT = 2.4;
export const EXHAUSTION_EMA20_PARABOLIC_PERCENT = 3.1;
export const EXHAUSTION_ATR_EXPANSION_EXTENDED = 1.2;
export const EXHAUSTION_ATR_EXPANSION_EXHAUSTED = 1.45;
export const EXHAUSTION_ATR_EXPANSION_PARABOLIC = 1.7;
export const EXHAUSTION_CLIMAX_VOLUME_EXTENDED = 1.4;
export const EXHAUSTION_CLIMAX_VOLUME_EXHAUSTED = 1.8;
export const EXHAUSTION_CLIMAX_VOLUME_PARABOLIC = 2.3;

export const DECISION_ADJ_CLEAN_BOS = 10;
export const DECISION_ADJ_BOS_STALE = 6;
export const DECISION_ADJ_CONFIRMED_RETEST = 8;
export const DECISION_ADJ_STRONG_STRUCTURE = 6;
export const DECISION_ADJ_SUPPORT_REJECTION = 5;
export const DECISION_ADJ_FAKE_BREAKDOWN = -20;
export const DECISION_ADJ_CHOCH_AGAINST = -15;
export const DECISION_ADJ_STRONG_SUPPORT_NEARBY = -12;
export const DECISION_ADJ_EXHAUSTION = -10;
export const DECISION_ADJ_PARABOLIC = -14;
export const DECISION_ADJ_COMPRESSION = -8;

export const MARKET_STRUCTURE_EMA20_FLAT_THRESHOLD = 0.08;
export const MARKET_STRUCTURE_EMA20_STRONG_RISE_THRESHOLD = 0.3;
export const MARKET_STRUCTURE_EMA20_STRONG_DOWN_THRESHOLD = -0.3;
export const MARKET_STRUCTURE_EMA20_SLIGHT_DOWN_THRESHOLD = -0.05;
export const MARKET_STRUCTURE_EMA200_SLOPE_UP_THRESHOLD = 0.02;
export const MARKET_STRUCTURE_EMA200_SLOPE_DOWN_THRESHOLD = -0.02;
export const MARKET_STRUCTURE_EMA200_TEST_DISTANCE_PERCENT = 0.8;

export const MARKET_STRUCTURE_TREND_ADJUSTMENTS = {
  StrongBearish: 8,
  Bearish: 4,
  TransitionalBearish: 0,
  Neutral: -6,
  TransitionalBullish: -10,
  Bullish: -20,
  StrongBullish: -30
} as const;

export const MARKET_STRUCTURE_ENTRY_SCORE_CAPS = {
  Neutral: 40,
  Bullish: 20,
  StrongBullish: 0
} as const;

export const MARKET_QUALITY_DEFAULT_MIN_MARKET_CAP_USD = 25_000_000;
export const MARKET_QUALITY_DEFAULT_MIN_VOLUME_USD = 10_000_000;

export const MARKET_QUALITY_MARKET_CAP_SCORES = {
  megaCap: 15,
  largeCap: 10,
  midCap: 5,
  smallCap: 2,
  microCap: -15
} as const;

export const MARKET_QUALITY_VOLUME_SCORES = {
  ultra: 10,
  high: 8,
  medium: 5,
  low: 2,
  thin: -8
} as const;

export const MARKET_QUALITY_EXCELLENT_MIN = 85;
export const MARKET_QUALITY_GOOD_MIN = 70;
export const MARKET_QUALITY_AVERAGE_MIN = 55;
export const MARKET_QUALITY_RISKY_MIN = 35;
