import { CANDLE_DEFAULT_INTERVAL, CANDLE_INTERVALS } from '../../candles/constants/candle.constants.js';

export const INDICATOR_SUPPORTED_INTERVALS = CANDLE_INTERVALS;
export const INDICATOR_DEFAULT_INTERVAL = CANDLE_DEFAULT_INTERVAL;
export const INDICATOR_CANDLE_LIMIT = 250;

export const EMA_PERIODS = {
  ema9: 9,
  ema20: 20,
  ema200: 200
} as const;

export const TREND_VALUES = ['Bullish', 'Bearish', 'Neutral'] as const;

export const TREND_AGE_VALUES = ['Fresh', 'Developing', 'Old'] as const;

export const FRESH_CROSS_MAX_CANDLES = 8;
export const DEVELOPING_TREND_MAX_CANDLES = 20;

export const DISTANCE_BELOW_EMA200_BONUS_PERCENT = 3;
export const DISTANCE_BELOW_EMA200_PENALTY_PERCENT = 8;

export const SCORE_WEIGHTS = {
  belowEMA200: 25,
  bearishAlignment: 25,
  freshCross: 25,
  closeToEMA200: 25,
  farBelowEMA200Penalty: -20,
  oldTrendPenalty: -15
} as const;

export const SCORE_MIN = 0;
export const SCORE_MAX = 100;

export const EMA20_SLOPE_LOOKBACK = 5;
export const EMA200_SLOPE_LOOKBACK = 10;
export const EMA9_SLOPE_LOOKBACK = 5;
export const MOMENTUM_LOOKBACK = 5;

export const SLOPE_FLAT_THRESHOLD_PERCENT = 0.06;
export const SLOPE_STRONG_DOWN_THRESHOLD_PERCENT = -0.35;
export const SLOPE_MODERATE_DOWN_THRESHOLD_PERCENT = -0.12;
export const SLOPE_SCORE_FULL_DECLINE_PERCENT = 0.6;

export const SIDEWAYS_MAX_DISTANCE_FROM_EMA200_PERCENT = 1.2;
export const SIDEWAYS_OSCILLATION_LOOKBACK = 12;
export const SIDEWAYS_MIN_SIGN_FLIPS = 3;
export const SIDEWAYS_PRICE_SIGN_FLIPS_MIN = 4;
export const SIDEWAYS_TIGHT_RANGE_MAX_PERCENT = 1.4;
export const SIDEWAYS_LOW_ATR_MAX_PERCENT = 0.35;
export const SIDEWAYS_PENALTY_LIGHT = 10;
export const SIDEWAYS_PENALTY_MEDIUM = 18;
export const SIDEWAYS_PENALTY_HEAVY = 25;

export const VOLUME_AVERAGE_PERIOD = 20;
export const VOLUME_QUALITY_POOR_THRESHOLD = 0.8;
export const VOLUME_QUALITY_GOOD_THRESHOLD = 1.1;
export const VOLUME_QUALITY_EXCELLENT_THRESHOLD = 1.6;
export const VOLUME_SCORE_RATIO_EXCELLENT = 2.5;
export const VOLUME_SCORE_RATIO_STRONG = 2;
export const VOLUME_SCORE_RATIO_GOOD = 1.5;
export const VOLUME_SCORE_RATIO_FAIR = 1.2;
export const VOLUME_SCORE_RATIO_BASE = 1;

export const TREND_STRENGTH_MIN = 0;
export const TREND_STRENGTH_MAX = 10;

export const PRICE_EFFICIENCY_LOW_THRESHOLD = 0.8;
export const PRICE_EFFICIENCY_MEDIUM_THRESHOLD = 1.5;
export const MOMENTUM_SCORE_FULL_DECLINE_PERCENT = 3;

export const ELIGIBILITY_MIN_TREND_STRENGTH = 5;
export const ELIGIBILITY_MAX_SIDEWAYS_SCORE = 60;
export const ELIGIBILITY_MAX_DISTANCE_BELOW_EMA200_PERCENT = -3;
export const HIGH_PRIORITY_MAX_CANDLES_SINCE_CROSS = 3;
export const HIGH_PRIORITY_MIN_TREND_STRENGTH = 7;

export const SIDEWAYS_STAGE_MAX_SCORE = 60;
export const SIDEWAYS_STAGE_MIN_TREND_STRENGTH = 4;

export const EARLY_BREAKDOWN_MAX_CANDLES_SINCE_CROSS = 3;
export const EARLY_BREAKDOWN_MIN_TREND_STRENGTH = 7;
export const EARLY_BREAKDOWN_MAX_SIDEWAYS_SCORE = 20;

export const PULLBACK_ENTRY_MIN_CANDLES_SINCE_CROSS = 3;
export const PULLBACK_ENTRY_MAX_CANDLES_SINCE_CROSS = 12;
export const PULLBACK_ENTRY_MIN_TREND_STRENGTH = 6;
export const PULLBACK_ENTRY_MAX_SIDEWAYS_SCORE = 30;
export const PULLBACK_ENTRY_NEAR_EMA_MAX_DISTANCE_PERCENT = 0.8;

export const TREND_CONTINUATION_MIN_CANDLES_SINCE_CROSS = 13;
export const TREND_CONTINUATION_MIN_TREND_STRENGTH = 6;

export const LATE_TREND_OLD_MIN_CANDLES_SINCE_CROSS = 20;
export const LATE_TREND_DISTANCE_FROM_EMA200_PERCENT = -3;
export const LATE_TREND_LOW_PRICE_EFFICIENCY = 0.12;
export const LATE_TREND_WEAKENING_TREND_STRENGTH = 5;

export const ENTRY_STOP_BUFFER_PERCENT = 0.25;
export const ENTRY_SWING_LOOKBACK = 20;
export const ENTRY_SUPPORT_LOOKBACK = 20;
export const ENTRY_CONTINUATION_MAX_EMA20_DISTANCE_PERCENT = 1;
export const ENTRY_EARLY_BREAKDOWN_EXTENDED_DISTANCE_PERCENT = 1.5;
export const ENTRY_PULLBACK_NEAR_EMA9_DISTANCE_PERCENT = 0.5;

export const ENTRY_QUALITY_MAX = 100;
export const ENTRY_QUALITY_MIN = 0;
export const ENTRY_QUALITY_RR_HIGH = 3;
export const ENTRY_QUALITY_RR_MEDIUM = 2;
export const ENTRY_QUALITY_RR_LOW = 1.5;

export const TREND_SCORE_EXCELLENT_MIN = 85;
export const TREND_SCORE_GOOD_MIN = 70;
export const TREND_SCORE_AVERAGE_MIN = 55;

export const ENTRY_SCORE_READY_MIN = 80;
export const ENTRY_SCORE_WATCH_MIN = 65;
export const ENTRY_SCORE_DEVELOPING_MIN = 50;

export const VERDICT_READY_TREND_MIN = 85;
export const VERDICT_READY_ENTRY_MIN = 80;
export const VERDICT_DEVELOPING_TREND_MIN = 70;
